core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from .views.home import index, dashboard, revisoes, arearestrita
from .views.auth import *

urlpatterns = [
    path('accounts/login/', user_login, name='login'),
    path('accounts/logout/', user_logout, name='logout'),
    path('registro/', registro, name='registro'),
    path('', index, name='index'),
    path('dashboard/', dashboard, name='dashboard'),
    path('revisoes/', revisoes, name='revisoes'),
    path('arearestrita/',arearestrita, name='arearestrita'),
    path('profile/', profile, name='profile'),

]  

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    telefone = models.CharField(max_length=11)
    endereco = models.CharField(max_length=200)
    image = models.ImageField(default='perfil/img/personcircle.png', upload_to='perfil/img')

core/forms.py
from django.forms import ModelForm
from django import forms
from .models import Profile
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['email', 'endereco', 'telefone', 'image']
        

core/views/home.py
from datetime import date, timedelta, datetime
from django.db.models import Count
from django.shortcuts import render
from revisao.models import Revisao, Flashcard
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from core.views.auth import superuser
from materiais.models import *
from django.contrib.auth.models import User
from django.contrib import messages
from core.models import Profile
from questoes.views import grafico, estatisticas
from questoes.models import UserProfile
from django.db.models import Count
from django.db.models.functions import ExtractWeekDay

 
def index(request):
    return render(request, "index.html")

def home(request):
    return render(request, "core/home.html")

@login_required
def dashboard(request):
    user = request.user
    created = Profile.objects.get_or_create(user=user)
    todas_revisoes = Revisao.objects.filter(user=user, concluida=False, data_agendada__gte=date.today()).order_by('data_agendada')
    revisoes_do_dia = Revisao.objects.filter(user=user, data_agendada=date.today(), concluida=False)
    revisoes_pendentes = Revisao.objects.filter(user=user, data_agendada__lt=date.today(), concluida=False)
    revisao = Revisao.objects.filter(user=user, concluida=False, data_agendada__lte=date.today()).order_by('data_agendada').first()

    if request.user.is_authenticated:
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)

    acertos = user_profile.acertos
    erros = user_profile.erros

    if acertos + erros > 0:
        taxa_acerto = round((acertos / (acertos + erros)) * 100, 2)
    else:
       taxa_acerto = 0

    dados_revisoes = revisoes(user) 
    serialized_dataq = grafico(request)

    context = {
        'todas_revisoes': todas_revisoes,
        'revisoes_do_dia': revisoes_do_dia,
        'revisoes_pendentes': revisoes_pendentes,
        'dados_revisoes': dados_revisoes,
        'revisao': revisao,
        'serialized_dataq': serialized_dataq,
        'taxa_acerto': taxa_acerto,
    }

    return render(request, "core/pages/dashboard.html", context)


def revisoes(user):
    today = datetime.now().date()
    inicio = today - timedelta(days=today.weekday()) + timedelta(days=1)
    fim = inicio + timedelta(days=6)
    
    data = (
        Revisao.objects
        .filter(user=user, concluida=True, data_agendada__range=[inicio, fim])
        .values('data_agendada')
        .annotate(revisoes=Count('id'))
        .order_by('data_agendada')
    )

    dias = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb']
    revisoes_por_dia = [0] * len(dias)

    for item in data:
        data_agendada = item['data_agendada'] + timedelta(days=1)
        dia_da_semana = data_agendada.weekday()
        revisoes_por_dia[dia_da_semana] = item['revisoes']
 
    dados = {
        'dias': dias,  
        'revisoes': revisoes_por_dia
        }
    print(dados)
    return json.dumps(dados)
 

@user_passes_test(superuser)
def arearestrita(request):
    disciplinas = Disciplina.objects.all()
    assuntos = Assunto.objects.all()
    conteudos = Conteudo.objects.all()
    materiais = Materiais.objects.all()

    context = {
        'disciplinas': disciplinas,
        'assuntos': assuntos,
        'conteudos': conteudos,
        'materiais': materiais,
    }

    return render(request, 'core/pages/arearestrita.html', context)

core/templates/core/pages/arearestrita.html
{% extends 'base.html' %}
{% load static %}

{% block head%}
<link rel="stylesheet" href="{% static 'materiais\css\style.css' %}">

{% endblock %}

{% block title%} Área restrita{% endblock %}

{% block content %}
<div class="m-auto">


    <h1 class="d-flex justify-content-center p-5">Área restrita para administradores</h1>


    <br><br>
    <div class="m-auto" style="max-width: 500px;">
        <h4 class="d-flex justify-content-center">Disciplinas</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Mais</th>
                </tr>
            </thead>
            <tbody>
                {% for disciplina in disciplinas %}
                <tr>
                    <th scope="row">{{ disciplina.id }}</th>
                    <td>{{ disciplina.nome }}</td>

                    <td>
                        <a href="{% url 'disciplina_remover' id=disciplina.id %}">
                            <svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                <path
                                    d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
                            </svg>
                        </a>
                        <a href="{% url 'disciplina_editar' id=disciplina.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                <path
                                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001" />
                            </svg>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="bmateriais">
        <a  href="{% url 'disciplina_criar' %}">Adicionar Disciplinas</a>
            </div>

        <br><br> <br><br>
        <h4 class="d-flex justify-content-center">Assuntos</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Mais</th>
                </tr>
            </thead>
            <tbody>
                {% for assunto in assuntos %}
                <tr>
                    <th scope="row">{{ assunto.id }}</th>
                    <td>{{ assunto.nome }}</td>
                    <td>
                        <a href="{% url 'assunto_remover' id=assunto.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                width="16" height="16" fill="currentColor" class="bi bi-trash3-fill"
                                viewBox="0 0 16 16">
                                <path
                                    d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
                            </svg>
                        </a>
                        <a href="{% url 'assunto_editar' id=assunto.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                <path
                                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001" />
                            </svg>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="bmateriais">
        <a  href="{% url 'assunto_criar' %}">Adicionar Assuntos</a>
            </div>

        <br><br> <br><br>
        <h4 class="d-flex justify-content-center">Conteúdos</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Mais</th>
                </tr>
            </thead>
            <tbody>
                {% for conteudo in conteudos %}
                <tr>
                    <th scope="row">{{ conteudo.id }}</th>
                    <td>{{ conteudo.nome }}</td>
                    <td>
                        <a href="{% url 'conteudo_remover' id=conteudo.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                width="16" height="16" fill="currentColor" class="bi bi-trash3-fill"
                                viewBox="0 0 16 16">
                                <path
                                    d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
                            </svg>
                        </a>
                        <a href="{% url 'conteudo_editar' id=conteudo.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                <path
                                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001" />
                            </svg>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="bmateriais">
        <a  href="{% url 'conteudo_criar' %}">Adicionar Conteúdos</a>
            </div>


        <br><br> <br><br>
        <h4 class="d-flex justify-content-center">Materiais</h4>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Título</th>
                    <th scope="col">Mais</th>
                </tr>
            </thead>
            <tbody>
                {% for material in materiais %}
                <tr>
                    <th scope="row">{{ material.id }}</th>
                    <td>{{ material.titulo }}</td>
                    <td>
                        <a href="{% url 'materiais_remover' id=material.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                width="16" height="16" fill="currentColor" class="bi bi-trash3-fill"
                                viewBox="0 0 16 16">
                                <path
                                    d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5" />
                            </svg>
                        </a>
                        <a href="{% url 'materiais_editar' id=material.id %}">                 
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                <path
                                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001" />
                            </svg>
                        </a>
                    </td> 
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="bmateriais">
        <a  href="{% url 'materiais_criar' %}">Adicionar Materiais</a>
            </div>

        
            <br><br> <br><br>
        






{% endblock %}

core/templates/core/pages/dashboard.html
{% extends 'core/partials/base.html' %}
{% load static %}

{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{% endblock %}

{% block title%} Dashboard {% endblock %}

{% block linkh %}ativo{% endblock %} 

{% block content %} 
<br>
<div class="d-flex mt-3 container  mainc">
    <div class="">
        <div class="d-flex msgbv">
            <div>
                <h1>E aí, {{user.username}}!</h1>
                {% if revisoes_do_dia.count > 0 and revisoes_pendentes.count > 0 %}
                    {% if revisoes_do_dia.count == 1 %}
                        {% if revisoes_pendentes.count == 1 %}
                            <p>No dia de hoje, está disponível 1 flashcard para revisão, mas não se esqueça do flashcard atrasado. Eles estão na beira da curva do esquecimento. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                        {% else %}
                            <p>No dia de hoje, está disponível 1 flashcard para revisão, mas não se esqueça dos {{ revisoes_pendentes.count }} flashcards atrasados. Eles estão na beira da curva do esquecimento. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                        {% endif %}
                    {% else %}
                        {% if revisoes_pendentes.count == 1 %}
                            <p>No dia de hoje, estão disponíveis {{ revisoes_do_dia.count }} flashcards para revisão, mas não podemos esquecer do flashcard atrasado. Ele está na beira da curva do esquecimento. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                        {% else %}
                            <p>No dia de hoje, estão disponíveis {{ revisoes_do_dia.count }} flashcards para revisão, mas não podemos esquecer dos {{ revisoes_pendentes.count }} flashcards atrasados. Eles estão na beira da curva do esquecimento. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                        {% endif %}
                    {% endif %}
                {% elif revisoes_do_dia.count == 0 and revisoes_pendentes.count > 0 %}
                    {% if revisoes_pendentes.count == 1 %}
                        <p>Você possui 1 flashcard atrasado. Ele está na beira da curva do esquecimento. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                    {% else %}
                        <p>Você possui {{ revisoes_pendentes.count }} flashcards atrasados. Eles estão na beira da curva do esquecimento. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                    {% endif %}
                {% elif revisoes_do_dia.count > 0 and revisoes_pendentes.count == 0 %}
                    {% if revisoes_do_dia.count == 1 %}
                        <p>No dia de hoje, está disponível 1 flashcard para revisão. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                    {% else %}
                        <p>No dia de hoje, estão disponíveis {{ revisoes_do_dia.count }} flashcards para revisão. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                    {% endif %}
                {% else %}
                    <p>Não há nenhuma revisão no dia de hoje. Além disso, sua taxa de acerto nas questões é de {{ taxa_acerto }}%.</p>
                {% endif %}
            </div>
            <div class="msgimg">
                <img src="{% static 'core/img/image 3.png' %}" alt="">
            </div>
        </div>

        <div class="d-flex mt-5 graficos">
            <div class="grafico">
                {% include 'questoes/partials/grafico.html' %}
            </div>    

            <div class="grevisao">
                {% include 'revisao/grafico.html' %}
            </div>
        </div>
    </div>

    <div class="lado2">
        <div class="fage">
            <h1 class="d-flex justify-content-center">Flashcards Agendados</h1>
        </div>

        <div class="d-flex mainfatri">
            <div class="fatri">
                <h1>{{todas_revisoes.count}}</h1>
                <p>Atribuídos</p>
            </div>

            <div class="fatri">
                <h1>{{revisoes_pendentes.count}}</h1>
                <p>Pendentes</p>
            </div>
        </div>



        <div class="tabelare">
            <div class="d-flex titabelare">
                <h3 style="margin: auto;">Próximas Revisões</h3>
                <a class="lta" href="{% url 'calendario' %}">Veja mais &#8594;</a>
            </div>

            {% if revisao %}
            <div class="tabelar">
            <table class="table table-borderless">
                <tr class="ftr">
                    <th class="fth">Título</th>
                    <th class="fth data">Data</th>
                </tr>


                {% for revisao in revisoes_pendentes|slice:":5" %}
                <tr class="ftr">
                    <td class="ftd"><a
                            href="{% url 'detalhes_flashcard' id=revisao.flashcard.id %}">{{revisao.flashcard.titulo}}</a>
                    </td>
                    <td class="ftd data" id="pendentes">{{ revisao.data_agendada|date:"d/m/Y" }}</td>
                </tr>
                {% endfor %}

                
                {% if  revisoes_pendentes.count < 1 %}
                    {% for revisao in revisoes_do_dia|slice:":5" %}
                        <tr class="ftr">
                            <td class="ftd"> <a
                                    href="{% url 'detalhes_flashcard' id=revisao.flashcard.id %}">{{revisao.flashcard.titulo}}</a>
                            </td>
                            <td class="ftd data" id="atribuídas">{{ revisao.data_agendada|date:"d/m/Y" }}</td>
                        </tr>
                    {% endfor %}

                    {% elif revisoes_pendentes.count < 4 %}
                        {% for revisao in revisoes_do_dia|slice:":3" %}
                            <tr class="ftr">
                                <td class="ftd"> <a
                                        href="{% url 'detalhes_flashcard' id=revisao.flashcard.id %}">{{revisao.flashcard.titulo}}</a>
                                </td>
                                <td class="ftd" id="atribuídas">{{ revisao.data_agendada|date:"d/m/Y" }}</td>
                            </tr>
                        {% endfor %}                        
                {% endif %}               
                
            </table>
        </div>


            <div class="bcomecarev">
                <a href="{% url 'detalhes_flashcard' id=revisao.flashcard.id %}">Começar revisão</a>
            </div>



            {% else %}
            <div class="nhra">
                <p>Não há revisões agendadas</p>
            </div>
            {% endif %}


        </div>

        <br>
    </div>


    {% endblock %}

core/templates/core/pages/perfil.html
{% extends 'core/partials/base.html' %}
{% load static %}
{% block title%} Perfil {% endblock %}
{% block content %}
<div class="container pcontainer" >
<div class=" bg-white d-flex align-items-center quebrar" >
        <div class="" >
            <img style="margin-right: 20px;" class="imgperfil" src="{{ user.profile.image.url }}" alt="{{ user.username }}">
        </div> 
    
        <div class="infos" id="infosSection">
            <p class="fw-semibold m-0"> Nome:</p>
            <p class="fw-lighter"> {{user.username}}</p>
    
            <p class="fw-semibold m-0"> Email:</p>
            <p class="fw-lighter"> {{user.profile.email}}</p>
    
            <p class="fw-semibold m-0"> Endereço:</p>
            <p class="fw-lighter">{{user.profile.endereco}}</p>
    
            <p class="fw-semibold m-0"> Telefone:</p>
            <p class="fw-lighter">{{user.profile.telefone}}</p>
            <a class="btn btn-outline-secondary" href="#"> <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512"> <path fill="#4e4e50" d="M362.7 19.3L314.3 67.7 444.3 197.7l48.4-48.4c25-25 25-65.5 0-90.5L453.3 19.3c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2C-1.5 489.7 .8 498.8 7 505s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L421.7 220.3 291.7 90.3z" /> </svg> Editar Perfil</a>
        </div>
        
        <div class="forms sumir" id="formsSection">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label" for="id_email">Email:  </label>
                    <div class="col-sm-10">
                        <input class="form-control" type="email" name="email" maxlength="254"
                               value="{{user.profile.email}}" required="" id="id_email">
                    </div>
                </div>
    
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label" for="id_endereco">Endereço:  </label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" name="endereco" maxlength="200"
                               required="" id="id_endereco" value="{{user.profile.endereco}}">
                    </div>
                </div>
    
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label" for="id_telefone">Telefone:  </label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" name="telefone" maxlength="11"
                               required="" id="id_telefone" value="{{user.profile.telefone}}">
                    </div>
                </div>
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label" for="id_image">Foto:  </label>
                    <div class="col-sm-10">
                        <input class="form-control" type="file" name="image" accept="image/*"
                               id="id_image">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Editar</button>
            </form>
        </div>
    </div>
</div>

<br>
<br>
<br>
<br>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const infos = document.querySelector('.infos');
            const form = document.querySelector('form');
    
            infos.addEventListener('click', function (event) {
                event.preventDefault();
                document.getElementById('infosSection').classList.add('sumir');
                document.getElementById('formsSection').classList.remove('sumir');
            });
    
            form.addEventListener('submit', function () {
                document.getElementById('infosSection').classList.remove('sumir');
                document.getElementById('formsSection').classList.add('sumir');
            });
        });
    </script>

{% endblock %}